# Test data for Project Notifier tests

INSERT INTO PROJECT_NOTIFIER 
  (ID, DATE_CREATED, DATE_UPDATED, MODEL_ENCODING, FLG_ENABLED, NOTIFIER_ORIGIN, RECIPIENT_TYPE, FLG_SEND_ON_ERROR,FLG_SEND_ON_FAILURE, FLG_SEND_ON_SUCCESS, FLG_SEND_ON_WARNING)
  VALUES (100, 2007-11-01, 2007-11-10, 'UTF-8', 1, 1, 1 , 1, 0, 0, 0 )