# Drops all tables

drop table BUILDDEFINITION;
drop table BUILDRESULT;
drop table BUILDRESULT_MODIFIEDDEPENDENCIES;
drop table CHANGEFILE;
drop table CHANGESET;
drop table CONTINUUMMODELLOMETADATA;
drop table INSTALLATION;
drop table NOTIFICATIONADDRESS;
drop table NOTIFICATIONADDRESS_CONFIGURATION;
drop table PROFILE;
drop table PROJECT;
drop table PROJECTDEPENDENCY;
drop table PROJECTDEVELOPER;
drop table PROJECTGROUP;
drop table PROJECTGROUP_BUILDDEFINITIONS;
drop table PROJECTGROUP_NOTIFIERS;
drop table PROJECTNOTIFIER;
drop table PROJECTNOTIFIER_CONFIGURATION;
drop table PROJECT_BUILDDEFINITIONS;
drop table PROJECT_NOTIFIERS;
drop table SCHEDULE;
drop table SCMRESULT;
drop table SUITERESULT;
drop table SYSTEMCONFIGURATION;
drop table TESTCASEFAILURE;
drop table TESTRESULT;